### ISSUE TITLE
Automated Recurring billing support

### ISSUE THREAD

**Issue by Moeez007** [AuthorizeNet/accept-sdk-ios#18]
Hello Guys,

I have been using the inperson sdk for authorize.net for iOS and it works fine. There is one issue that the inperson sdk does not have Automated Recurring Billing. My question is that does this sdk provides support for ARB. Thanks. 

Any help would be appreciated.

**Comment by ptaneja** [comment]
As of now we don't have ARM feature inside SDK? This is on our future road map.
