### ISSUE TITLE
Trying to install via Cocoapods and import not working with Swift 3.0.1

### ISSUE THREAD

**Issue by philipsawyer** [AuthorizeNet/accept-sdk-ios#22]
Just updated to Xcode v8.1 and am trying to install the AcceptSDK pod. However, once I import it, Xcode gives me an error saying Module Compiled with Swift 3.0 cannot be imported in Swift 3.0.1 and then a path to the module.

I have tried saying Use Legacy Swift Language Version however this does not solve the issue.

**Comment by rajmohangoaugment** [comment]
@philipsawyer did you manage to resolve this issue, if yes can you post the possible work around ?

**Comment by albertcabello** [comment]
@philipsawyer @rajmohangoaugment Have you guys found a workaround?  I'm getting the exact same error message excepts for me it's Swift 3.0.2.

**Comment by rajmohangoaugment** [comment]
@albertcabello not yet, I ended up adding accept-sdk as a source code dependency using a forked repo

**Comment by albertcabello** [comment]
@rajmohangoaugment How did you do that?  I tried forking the repo, cloning it, rebuilding it, and referencing the local framework and that didn't work either.

**Comment by ak2g** [comment]
remove all import and drag and drop AcceptSDK and AcceptSDK-Framework folder to your project and change file permissions to read and write and this should work

**Comment by ptaneja** [comment]
@albertcabello Looks like you got it working. Please reopen the issue if you are still facing the issue.
