### ISSUE TITLE
Processing for payment

### ISSUE THREAD

**Issue by bala-ski** [AuthorizeNet/accept-sdk-ios#25]
Using the accept token what are the methods to call for processing the payment.

**Comment by bala-ski** [comment]
For processing the payment, while sending the request we need to use the method "fingerPrint" for adding amount and currency code.

```
let request = AcceptSDKRequest()
request.merchantAuthentication.fingerPrint?.amount = "50" request.merchantAuthentication.fingerPrint?.currencyCode = "$"
```

and i need the details for the hashValue and sequence.

**Comment by brianmc** [comment]
You don't need any fingerprint to process the transaction (or get the token).  Simply use our createTransaction API from your mobile backend server: http://developer.authorize.net/api/reference/index.html#mobile-inapp-transactions
