### ISSUE TITLE
CIM - Add credit card to a profile

### ISSUE THREAD

**Issue by deepakssn** [AuthorizeNet/accept-sdk-ios#26]
I have CIM and I want to save the cards to customer profile. I want methods to save cards in customer profiles and get a token in response that can be used for future transactions by the customer.

**Comment by RakeshVisa** [comment]
Hi @deepakssn, accept-sdk-ios is not meant for CIM and customer profile related things. Please use any other AuthorizeNet sdks for this purpose (like sdk-php, sdk-python).
