### ISSUE TITLE
How to import AcceptSDK into project-Swift2.3

### ISSUE THREAD

**Issue by CHINAZB** [AuthorizeNet/accept-sdk-ios#29]
Hi,man

What can I do that importing "AcceptSDK" into my project with Swift2.3 ？ Do you have any other
version of SDK?

Look forward to your reply，thanks very much !

**Comment by ptaneja** [comment]
Are you still facing the issue? Could you please update Xcode and try?

**Comment by CHINAZB** [comment]
It can work in my application after update Xcode & swift ，thanks @ptaneja
