### ISSUE TITLE
Any idea when the framework will be upgraded to Swift 3.1

### ISSUE THREAD

**Issue by spr-ronpark** [AuthorizeNet/accept-sdk-ios#32]
Requiring the use of Accept SDK on iOS for 3.1. Unable to install old 3.0.0 toolchain into project.

**Comment by sagarmilani** [comment]
@RakeshVisa @brianmc @kbollepa I am also facing the same issue, any idea how to solve it? @spr-ronpark how you soled it?

**Comment by kylehorn** [comment]
I'm facing the same issue, with 3.2 now.

**Comment by kylehorn** [comment]
Is there any update on this?

**Comment by hemraj-shaqawal** [comment]
I'm facing the same issue, with 3.1 now. so anyone has idea how to resolve this.

**Comment by RakeshVisa** [comment]
We have updated the framework to Swift 4. Please let us know whether you are still facing this issue.
