### ISSUE TITLE
Getting error while submitting application to app store

### ISSUE THREAD

**Issue by ketan-parmar** [AuthorizeNet/accept-sdk-ios#37]
I am facing multiple issues when uploading my application on app store. I have my project in objective c and i have integrated accept-ios SDK manually, I mean i haven't used pod. Because when i have tried to use accept-ios SDK with pod it was unable to compile. any solution for uploading app to appstore !

I got errors like,

    ERROR ITMS-90087: "Unsupported Architectures. The executable for AuthorizedDemoLatest.app/Frameworks/AcceptSDK.framework contains unsupported architectures '[x86_64, i386]'."

    ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'AuthorizedDemoLatest.app/Frameworks/AcceptSDK.framework/AcceptSDK' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."

    ERROR ITMS-90125: "The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker."

    ERROR ITMS-90206: "Invalid Bundle. The bundle at 'AuthorizedDemoLatest.app/Frameworks/AcceptSDK.framework' contains disallowed file 'Frameworks'."

**Comment by sagarmilani** [comment]
@RakeshVisa @brianmc @kbollepa I am also facing the same issue, any idea how to solve it? @ketan-parmar any luck?

**Comment by kylehorn** [comment]
I'm also running into the same issue.

**Comment by Mindbowser** [comment]
@ketan-parmar any luck?

**Comment by kylehorn** [comment]
Still getting the error, can't submit to the store.

**Comment by ptaneja** [comment]
@ketan-parmar @sagarmilani @kylehorn @Mindbowser Could you please try the 0.0.9 version? If you still face the issue, please follow this link http://ikennd.ac/blog/2015/02/stripping-unwanted-architectures-from-dynamic-libraries-in-xcode/

**Comment by kylehorn** [comment]
@ptaneja Still getting the error when submitting to the App Store.

**Comment by ptaneja** [comment]
Either you can follow the link http://ikennd.ac/blog/2015/02/stripping-unwanted-architectures-from-dynamic-libraries-in-xcode/ or check out the source code and build it. Cocoa Pods doesn't allow me to push build without simulator binary.

**Comment by ptaneja** [comment]
Included archived zip with the release 0.0.9, this build doesn't have simulator binary symbols. You could try including this https://github.com/AuthorizeNet/accept-sdk-ios/releases/tag/0.0.9

**Comment by kylehorn** [comment]
@ptaneja This fixed most of the issues, but there is one remaining that says it includes the disallowed folder `Frameworks`.

**Comment by ptaneja** [comment]
@kylehorn, Toggled the Embed Swift Project off and it stripped off the Framework folder, Could you please try including the archived zip from the link, updated the release
https://github.com/AuthorizeNet/accept-sdk-ios/releases/tag/0.0.9

**Comment by ketan-parmar** [comment]
@sagarmilani @Mindbowser , Sorry for late reply but i had used apis provided by [Authorized.net](https://developer.authorize.net/api/reference/index.html) . But as @ptaneja  saying, If issue is resolved than we can use sdk!

**Comment by kuldeep13990** [comment]
I am getting this error with bitcode.

bitcode bundle could not be generated because '/Users/a123/Documents/iOS/Projects/RESET IV/Latest Project/ResetIV/Pods/AuthorizeNetAccept/AcceptSDK-Framework/AcceptSDK.framework/AcceptSDK' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/Users/a123/Documents/iOS/Projects/RESET IV/Latest Project/ResetIV/Pods/AuthorizeNetAccept/AcceptSDK-Framework/AcceptSDK.framework/AcceptSDK' for architecture arm64

How can I fix this?

**Comment by RakeshVisa** [comment]
Please use the latest SDK and let us know whether you are facing the same issue.
