### ISSUE TITLE
AcceptSDKRequest is not working in swift 3.1

### ISSUE THREAD

**Issue by hemraj-shaqawal** [AuthorizeNet/accept-sdk-ios#38]
I have imported "accept-sdk-ios" and view controller code in swift 3 project but AcceptSDKRequest is not working.is there any update in framework please let me know if anyone has idea about it.
thanks in advance

**Comment by ptaneja** [comment]
Could you please use the updated one? If you are using PODS, please run pod repo update first.

**Comment by CHINAZB** [comment]
@ptaneja Hi,man. I have got opaqueData & dataValue, but I do not know how the next step will be done，sent them to our company's server or "https://apitest.authorize.net/xml/v1/request.api"; I don't know what parameter should I sent neither.Looking forward to your reply.

**Comment by Arumugaraj1234** [comment]
@CHINAZB  Hi, did you get any solution..?same here..

**Comment by CHINAZB** [comment]
@Arumugaraj1234 show u the parameters I send to our server (The action of the transaction is done by our company's server) :
let paramStr = String(format:"key=%@&pay_sn=%@&payment_code=%@&dataValue=%@",key,self.pay_sn,"authorizep",inResponse.getOpaqueData().getDataValue())

**Comment by Arumugaraj1234** [comment]
@CHINAZB  thanks a lot..and one more issue.When I'm checking with testing credit cards each time Im getting the same data value. Any suggestion...?

**Comment by CHINAZB** [comment]
@Arumugaraj1234 Look carefully, the data is not the same in the middle。。

**Comment by Arumugaraj1234** [comment]
@CHINAZB  what is the kclientname in the AcceptSDK sample IOS App...Do you have any idea..?

**Comment by RakeshVisa** [comment]
We have updated our SDK. Please update the pod and try again. If you still face the problem please get back to us.
