### ISSUE TITLE
AcceptSDKHandler: Cannot find Swift declaration

### ISSUE THREAD

**Issue by AtulKrP** [AuthorizeNet/accept-sdk-ios#39]
I have installed through pod. Imported the AcceptSDK but getting this error.
 
'AcceptSDKHandler' is unavailable: cannot find Swift declaration for this class

I am not able to  figure out what's wrong

**Comment by ptaneja** [comment]
Could you please try on device instead of Simulator?

**Comment by AtulKrP** [comment]
Thanks. It worked
