### ISSUE TITLE
Cannot run on simulator

### ISSUE THREAD

**Issue by kylehorn** [AuthorizeNet/accept-sdk-ios#40]
I'm having issues when building for the simulator. I know there was an issue in the past to get it working for both but was wondering if there is an update on this? I need to build on the simulator to test different screen sizes. 

Please let me know if there is any update on this.

**Comment by ptaneja** [comment]
Use 0.2.0. 

If you face problem uploading to app store, then please use the script to remove simulator symbols or use the zipped framework attached to this release as an attachment.

**Comment by kylehorn** [comment]
I'm still getting the issue when I use cocoa pods to install the SDK.

**Comment by ptaneja** [comment]
what is the issue?

**Comment by kylehorn** [comment]
<img width="1775" alt="screenshot 2017-10-25 11 49 02" src="https://user-images.githubusercontent.com/1151101/32011475-84f9b766-b97a-11e7-81b8-023a4e23ab6a.png">

**Comment by kylehorn** [comment]
It only happens when I run on the simulator, it works fine on the device.

I am importing the project at the top of the file as well. I also get the same error when I do 
`AcceptSDKHandler(environment: env)`

**Comment by ptaneja** [comment]
Did we update the local pod repo and updated accept-sdk-ios to 0.2.0?

**Comment by ptaneja** [comment]
Closing.

**Comment by kylehorn** [comment]
@ptaneja I pointed Cocoapods to use the branch `master` and it worked.

Are there plans to continue maintaining development on this project to support newer versions of swift more out of the box?

**Comment by ptaneja** [comment]
@kylehorn Yes, we will be up-to date.
