### ISSUE TITLE
Please update to provide support for Swift 4.0.2 / XCode 9.1

### ISSUE THREAD

**Issue by hatboyzero** [AuthorizeNet/accept-sdk-ios#41]
Please update this pod with a build compatible with Swift 4.0.2 / XCode 9.1.

**Comment by Junaidtt** [comment]
We are eagerly waiting to update this pod  compatiable for Swift 4 and Xcode 9.1

**Comment by kuldeep13990** [comment]
@hatboyzero I am getting this error with bitcode.

**bitcode bundle could not be generated because '/Users/a123/Documents/iOS/Projects/RESET IV/Latest Project/ResetIV/Pods/AuthorizeNetAccept/AcceptSDK-Framework/AcceptSDK.framework/AcceptSDK' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/Users/a123/Documents/iOS/Projects/RESET IV/Latest Project/ResetIV/Pods/AuthorizeNetAccept/AcceptSDK-Framework/AcceptSDK.framework/AcceptSDK' for architecture arm64**

How can I fix this?

**Comment by Beautistar** [comment]
Same here, waiting swift last version updating.
Thanks

**Comment by Junaidtt** [comment]
How can we update accept-sdk to swift 4. which is not working. I think Matthew Alan Gray hatboyzero can help us in this case

**Comment by Junaidtt** [comment]
Module compiled with Swift 4.0.2 cannot be imported in Swift 4.1: @hatboyzero ??

**Comment by Junaidtt** [comment]
Hi

I really in a trouble after updating Xcode to 9.3 where AuthorizeNetAccept pod is not working.
Do you have any solution. Your help will be highly great



Regard 

Junaid

**Comment by RakeshVisa** [comment]
Hi @Junaidtt, @hatboyzero, @Beautistar, @kuldeep13990. We have updated our SDK. Please update the pod and try again. If you still face the problem please get back to us.

**Comment by tusharchetu** [comment]
> @hatboyzero I am getting this error with bitcode.
> 
> **bitcode bundle could not be generated because '/Users/a123/Documents/iOS/Projects/RESET IV/Latest Project/ResetIV/Pods/AuthorizeNetAccept/AcceptSDK-Framework/AcceptSDK.framework/AcceptSDK' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/Users/a123/Documents/iOS/Projects/RESET IV/Latest Project/ResetIV/Pods/AuthorizeNetAccept/AcceptSDK-Framework/AcceptSDK.framework/AcceptSDK' for architecture arm64**
> 
> How can I fix this?

did you solve this issue ?
if yes ! tell me steps please

**Comment by tusharchetu** [comment]
Hey kuldeep13990

> @hatboyzero I am getting this error with bitcode.
> 
> **bitcode bundle could not be generated because '/Users/a123/Documents/iOS/Projects/RESET IV/Latest Project/ResetIV/Pods/AuthorizeNetAccept/AcceptSDK-Framework/AcceptSDK.framework/AcceptSDK' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/Users/a123/Documents/iOS/Projects/RESET IV/Latest Project/ResetIV/Pods/AuthorizeNetAccept/AcceptSDK-Framework/AcceptSDK.framework/AcceptSDK' for architecture arm64**
> 
> How can I fix this?
