### ISSUE TITLE
AcceptSDK not Working in iOS Swift  4.1 new release. Update Pod

### ISSUE THREAD

**Issue by Junaidtt** [AuthorizeNet/accept-sdk-ios#53]
When I tried to update my Xcode  it is noticed that acceptSDK throwing  Ann error .How can I solve this iussue??/
Error Details is 
Module compiled with Swift 4.0 cannot be imported in Swift 4.1: /Users/bespokino/Desktop/bespokino/ios/Bespokino/Pods/AuthorizeNetAccept/AcceptSDK-Framework/AcceptSDK.framework/Modules/AcceptSDK.swiftmodule/x86_64.swiftmodule

**Comment by RakeshVisa** [comment]
Hi @Junaidtt, We have updated our SDK. Please update the pod and try again. If you still face the problem please get back to us.
