### ISSUE TITLE
updating required :

### ISSUE THREAD

**Issue by Junaidtt** [AuthorizeNet/accept-sdk-ios#54]
Module compiled with Swift 4.0 cannot be imported in Swift 4.1:

**Comment by mohammadkalim** [comment]
Module compiled with Swift 4.0 cannot be imported in Swift 4.1

**Comment by Junaidtt** [comment]
@mohammadkalim Have you got any updates on this issues "Module compiled with Swift 4.0.2 cannot be imported in Swift 4.1:"

**Comment by RakeshVisa** [comment]
We have updated our SDK. Please update the pod and try again. If you still face the problem please get back to us.
