### ISSUE TITLE
Module compile can not be imported error after updating xCode from 9.2 to 9.3.

### ISSUE THREAD

**Issue by kuldeep13990** [AuthorizeNet/accept-sdk-ios#55]
AcceptSDK integration working fine in xCode 9.2 version. Recently I updated my xCode from 9.2 to 9.3 and suddenly I am getting an error.

> **Module compiled with Swift 4.0.2 cannot be imported in Swift 4.1: /Volumes/Data/Reset IV 1.0/Current/ResetIV 2/AcceptSDK.framework/Modules/AcceptSDK.swiftmodule/x86_64.swiftmodule**

How can I fix this?
Any help will be appreciated.
Thanks

**Comment by laeroah** [comment]
Any updates on this one?

**Comment by laeroah** [comment]
Anyone from Authorize team here? hello?

**Comment by Junaidtt** [comment]
don't know? l have faced this issue when swift 4.0.1 was released. I think @hatboyzero can help  us in this case.

**Comment by niravdaamania** [comment]
anyone have the solution for the same ?

**Comment by RakeshVisa** [comment]
We have updated our SDK. Please update the pod and try again. If you still face the problem please get back to us.
