### ISSUE TITLE
App crashes when integrated in Objective C project

### ISSUE THREAD

**Issue by bhavinmdesai** [AuthorizeNet/accept-sdk-ios#57]
When I add it as a pod dependency and run my code, it crashes with following error:

```
Error :  dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /private/var/containers/Bundle/Application/E1DE15B0-855A-493B-98BA-C9FEA3AA0F29/accept-sample-objc.app/Frameworks/AcceptSDK.framework/AcceptSDK
  Reason: image not found
```

Please help how to fix it.

**Comment by RakeshVisa** [comment]
Hi @bhavinmdesai, We have updated our SDK. Please update the pod and try again (make sure you run pod repo update first). If you still face the problem please get back to us.

**Comment by bhavinmdesai** [comment]
@RakeshVisa Here are the steps that we did:
1. Update pods using `pod update`
2. Got following error:
> Pods written in Swift can only be integrated as frameworks; add `use_frameworks!` to your Podfile or target to opt into using it. The Swift Pod being used is: AuthorizeNetAccept
3. Added `use_frameworks!` line in the podfile as suggested above
4. Updated the pod again  `pod update`
5. Compiled the project again, which gives following error
> The "Swift Language Version" (`SWIFT_VERSION`) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.
6. Updated pod repo using `pod repo update`

**Still getting the same error as Step-5 and unable to find option "Swift Language Version" (`SWIFT_VERSION`) in build settings.**

**Comment by bhavinmdesai** [comment]
@RakeshVisa I did:

1. pod install –repo-update
2. #include `AuthorizeNetAccept-Swift.h` into the ViewController where this SDK is being used.

But I am still getting:
> 'AuthorizeNetAccept-Swift.h' file not found`
