### ISSUE TITLE
How does this SDK work?

### ISSUE THREAD

**Issue by ninjarails** [AuthorizeNet/accept-sdk-ios#58]
I have been asking question on community channel how to implement Accept.js in React Native without any answer. I was successful to make a custom integration in React.js and now decided to implement this in React Native using Webview and just wondering if this repo also used Webview or similar solution. Because community said that Accept.js was designed to run on web browser.
All answers appreciated. Btw Thank you for the great work!

**Comment by ninjarails** [comment]
Also I have been looking at the codebase. Is there any Authorize.net API endpoint that I can hit from React Native? I think I can handle the error/success response myself.

**Comment by anuragg29** [comment]
You can find the API details on https://developer.authorize.net/api/reference/index.html

HTTP Request Method: POST


Sandbox API Endpoint: https://apitest.authorize.net/xml/v1/request.api

Production API Endpoint: https://api.authorize.net/xml/v1/request.api


XML Content-Type: text/xml

JSON Content-Type: application/json


API Schema (XSD): https://api.authorize.net/xml/v1/schema/AnetApiSchema.xsd
