### ISSUE TITLE
Compiler Error: Module compiled with Swift 4.0 cannot be imported in Swift 4.1

### ISSUE THREAD

**Issue by ArturBaghdas** [AuthorizeNet/accept-sdk-ios#59]
Please fix this issue

**Comment by RakeshVisa** [comment]
Hi @ArturBaghdas, We have updated our SDK. Please update the pod and try again. If you still face the problem please get back to us.

**Comment by tusharchetu** [comment]
Hey @ArturBaghdas did your issue get resolved ?

**Comment by ArturBaghdas** [comment]
Works fine, thanks
