### ISSUE TITLE
Manual Installation not working

### ISSUE THREAD

**Issue by RaviNguyen** [AuthorizeNet/accept-sdk-ios#60]
I followed "Manual Installation" and build have bug
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/apple/Library/Developer/CoreSimulator/Devices/8EF4129A-21AB-401E-B458-5545770A17B1/data/Containers/Bundle/Application/C1EBFECD-6107-42CB-AD37-E1ED4B2E3FD7/RetailerPOS.app/Frameworks/AcceptSDK.framework/AcceptSDK
  Reason: image not found

**Comment by RakeshVisa** [comment]
Hi @RaviNguyen. We have updated our SDK. Please update the pod and try again. If you still face the problem please get back to us.
