### ISSUE TITLE
App crashes when integrated in Objective C project

### ISSUE THREAD

**Issue by xhardcorex** [AuthorizeNet/accept-sdk-ios#63]
I have got message : The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor. Can you help me ? Obj-C project

**Comment by RakeshVisa** [comment]
Hi @xhardcorex, thanks for reaching out to us.
Did you tried running your pod repo update first? If not i would recommend you to update it and try again. If you still face any issues after that please refer our Objective-C integration sample code [https://github.com/AuthorizeNet/accept-sample-ios-objectivec] or reach out to us for further investigation.

**Comment by Magantiaruna** [comment]
successful execution of the project am getting this page and please guide me how can i get to know further that means transaction is done or not...


![img_5e59472ca5be-1](https://user-images.githubusercontent.com/5127063/41523414-8fe754ee-72f7-11e8-829d-d5744e6b0e35.jpeg)

**Comment by RakeshVisa** [comment]
Hi @Magantiaruna, 
After the token is receive, use create transaction request from your server with the token. https://developer.authorize.net/api/reference/#payment-transactions-create-an-accept-payment-transaction.
Closing this thread assuming you are able to get the token successfully.
