### ISSUE TITLE
The given data was not valid JSON

### ISSUE THREAD

**Issue by deepaksinghnegi** [AuthorizeNet/accept-sdk-ios#64]
Hi,

I'm new to this Payment api and struggling to implement the payment api. As it successfully generates the token but when I make transaction request as follows:

        let json =  """
          {
            "createTransactionRequest": {
              "merchantAuthentication": {
                "name": "xyzzy",
                "transactionKey": "xyzzy"
              },
              "refId": "123",
              "transactionRequest": {
                "transactionType": "authCaptureTransaction",
                "amount": \(Config.currentBooking.totalPrice),
                "payment": {
                  "opaqueData": {
                    "dataDescriptor": "COMMON.ACCEPT.INAPP.PAYMENT",
                    "dataValue": "PAYMENT_NONCE_GOES_HERE"
                  }
                }
              }
            }
          }
          """
  
          let jsonData = Data(json.utf8)
          do {
            let transaction = try JSONDecoder().decode(Transaction.self, from: jsonData)
            print(transaction)
            // encoding
            let encodedData = try JSONEncoder().encode(transaction)
            print(String(data: encodedData, encoding: .utf8)!)
            
          }
          catch {
            print(error)
          }
      })

It gives me following response:

dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "Invalid value around character 264." UserInfo={NSDebugDescription=Invalid value around character 264.})))

Not sure if it is happening due to JSON order. It's the recommended manner to request a transaction.

Please help. Thanks!!!

**Comment by RakeshVisa** [comment]
Hi @deepaksinghnegi, currently Anet APIs expects ordered JSON request. Can you please make sure your JSON request parameter order is same as mentioned in API document and try again?

**Comment by deepaksinghnegi** [comment]
HI @RakeshVisa Thanks for replying, actually I've already done that, and it's working fine. I also want to know if it is enough code to make a payment as I'm not getting any successful payment message, only the transaction key. If not what should be the next step to make payment. Thanks again.

Following is the response I'm getting
{"createTransactionRequest":{"merchantAuthentication":{"name":"xyz","transactionKey":"xyz"},"refId":"xyz","transactionRequest":{"transactionType":"authCaptureTransaction","amount":"40.0","payment":{"opaqueData":{"dataValue":"PAYMENT_NONCE_GOES_HERE","dataDescriptor":"COMMON.ACCEPT.INAPP.PAYMENT"}}}}}

**Comment by deepaksinghnegi** [comment]
Okay I got it, can you please provide any sample code in Swift/Objective-C to create an accept transaction as it's not given in the documentation, but in other languages?  
Thanks a lot.

**Comment by RakeshVisa** [comment]
@deepaksinghnegi, unfortunately we don't have sample code to try this out. But we feel it is fairly straight forward to implement using Swift/Objective-C. Since this issue is resolved i'm closing this ticket.
