### ISSUE TITLE
SDK not working

### ISSUE THREAD

**Issue by RaviNguyen** [AuthorizeNet/accept-sdk-ios#67]
I install SDK by Pod.
Import SDK in view controller success. #import <AuthorizeNetAccept/AuthorizeNetAccept-Swift.h>
But use one line code: AcceptSDKHandler *handler = [[AcceptSDKHandler alloc] initWithEnvironment:AcceptSDKEnvironmentENV_TEST];
and build. I see error:

![authorize net](https://user-images.githubusercontent.com/16332228/42307477-c4c32f86-805c-11e8-9645-063e587979a4.png)

Please support me.

**Comment by RakeshVisa** [comment]
We have updated the code to support Swift 4.2. Please try updating the repository.
