### ISSUE TITLE
Module compiled with Swift 4.0 cannot be imported in Swift 4.2

### ISSUE THREAD

**Issue by Matt2218** [AuthorizeNet/accept-sdk-ios#68]

**Comment by tusharchetu** [comment]
I am having this same issue. did you resolve it ? and if did how ?
Thanks

**Comment by nikitabelosludtcev** [comment]
I have the same issue.

**Comment by Matt2218** [comment]
This is still an issue for me. It's not working with the new Xcode 10.

**Comment by RakeshVisa** [comment]
We have updated the code to support Swift 4.2. Please try updating the repository.
