### ISSUE TITLE
Could not build Objective-C module 'AuthorizeNetAccept' Swift 4

### ISSUE THREAD

**Issue by BeSmartiOs** [AuthorizeNet/accept-sdk-ios#71]
Hello, I installed the SDK by Pod.
1) import AuthorizeNetAccept fails. Could not build Objective-C module 'AuthorizeNetAccept'

2) Swift Compiler issue: Cannot invoke initializer for type 'Range<_>' with an argument list of type '(Range<String._CharacterView.Index>)'

Any help please?
Thanks.

**Comment by RakeshVisa** [comment]
We have updated the code to support Swift 4.2. Please try updating the repository.

**Comment by tusharchetu** [comment]
hey @BeSmartiOs did you resolve your issue ?
